### ISSUE TITLE
Thristy turtle issues

### ISSUE THREAD

**Issue by hartontw** [rolandoislas/PeripheralsPlusOne#12]
MC: 1.12.2
Forge: 14.23.4.2705
CC: 1.80pr1
PPO: 1.12.2-1.1-build-T58

### Description
- Thristy turtle doesn't suck.

### Steps to Reproduce
1. Place turtle above of water source.
2. Call function turtle.suckDown()

### Description
- turtle.drain() returns error (attempt to call nil).

### Steps to Reproduce
1. Place a bucket of water in slot 1
2. Call function turtle.drain()

**Comment by opencma** [comment]
The peripheral needs to be wrapped. Commands are exposed by the peripheral, not the `turtle` API.
