### ISSUE TITLE
onAttachCapabilities causes NullPointerException with Minecolonies

### ISSUE THREAD

**Issue by Scarjit** [rolandoislas/PeripheralsPlusOne#17]
### Description
When logging in near a Minecolony, the game crashes if PeripheralsPlusOne is installed.

### Steps to Reproduce
1. Have a Modpack with only Minecolony
2. Build a colony
3. Add PeripheralsPlusOne
4. Try to join the Server again

**Expected behavior:**
It should not crash

**Actual behavior:**
It crashes

**Stacktrace (if applicable):** 
https://hastebin.com/wahafolebi.txt

**Version affected:** 
PeripheralsPlusOne-1.12.2-1.1-build-T58.jar

### Additional Information
We are using CC-Tweaked instead of the normal ComputerCraft, but i haven't had issues with CC-Tweaked and PeripheralsPlusOne before.

**Comment by opencma** [comment]
The bug is fixed in the latest version of Minecolonies.
