### ISSUE TITLE
Peripheral Container in Pocket Computer only shows one peripheral

### ISSUE THREAD

**Issue by JomerDev** [rolandoislas/PeripheralsPlusOne#18]
### Description
Peripheral Container in Pocket Computer only shows one peripheral

### Steps to Reproduce
Craft Pocket Computer with Peripheral Container
Craft result with wireless modem
Craft result with speaker

Call container.getContainedPeripherals() =>It only ever shows the modem

...

**Expected behavior:** It should list all peripherals

**Actual behavior:** It only lists the first peripheral

**Version affected:** PeripheralsPlusOne-1.12.2-1.1-build-T58 *and* forge-14.23.5.2784

**Comment by opencma** [comment]
I cannot reproduce the bug.

**Comment by JomerDev** [comment]
It only happened when I crafted the same pocket computer seperately with the modem and the speaker. After a world reload everything is fine
