### ISSUE TITLE
mod doesn't load

### ISSUE THREAD

**Issue by AppliedEM** [rolandoislas/PeripheralsPlusOne#4]
### Description
When I install the mod and its required dependencies, it fails to load any of the items from the mod. 
I'm running a slightly modified version of the crackpack with the twitch client.

### Steps to Reproduce
1. Install the mod and "the framework" on the crackpack. load a single player world.
2. check NEI

...

**Version affected:** 
1.7.10

### Additional Information

**Comment by rolandoislas** [comment]
There is no version of PeripheralsPlusOne or TheFramework for 1.7.
